In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
import zipfile
import time

In [5]:
def load_imdb_data(req):
    url = 'https://arthursdata.blob.core.windows.net/datavis/title.{}.tsv.gz'.format(req)
    return pd.read_csv(link, sep='\t', index_col=0, compression='infer')

title_basics = load_imdb_data('basics')
title_episode = load_imdb_data('episodes')
title_ratings = load_imdb_data('ratings')

C:\Users\Arthur\AppData\Local\Temp\ipykernel_7524\2826404596.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(link, sep='\t', index_col=0, compression='infer')

In [6]:
title_basics.head()

,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
tconst,,,,,,,,
tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,\N
tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,\N
tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,\N
tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,\N
tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,\N

In [5]:
def load_strmsrvc_data(srvc_name):
    with zipfile.ZipFile('https://arthursdata.blob.core.windows.net/datavis/{}.zip'.format(srvc_name)) as f:
        titles_file = f.open('titles.csv')
        credits_file = f.open('credits.csv')
        
        title = pd.read_csv(titles_file, index_col=0)
        credit = pd.read_csv(credits_file, index_col=0)

        titles_file.close()
        credits_file.close()
    
    return {'titles':title, 'credits':credit}

ntfl = load_strmsrvc_data('ntfl')
amzn = load_strmsrvc_data('amzn')
crnc = load_strmsrvc_data('crnc')
dark = load_strmsrvc_data('dark')
dsny = load_strmsrvc_data('dsny')
hbo = load_strmsrvc_data('hbo')
hulu = load_strmsrvc_data('hulu')
prmt = load_strmsrvc_data('prmt')
raku = load_strmsrvc_data('raku')

dsny['titles'].head()

,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
id,,,,,,,,,,,,,,
tm74391,Fantasia,MOVIE,Walt Disney's timeless masterpiece is an extra...,1940,G,120,"['animation', 'family', 'music', 'fantasy']",['US'],NaN,tt0032455,7.7,94681.0,57.751,7.4
tm67803,Snow White and the Seven Dwarfs,MOVIE,"A beautiful girl, Snow White, takes refuge in ...",1937,G,83,"['fantasy', 'family', 'romance', 'animation', ...",['US'],NaN,tt0029583,7.6,195321.0,107.137,7.1
tm82546,Pinocchio,MOVIE,Lonely toymaker Geppetto has his wishes answer...,1940,G,88,"['animation', 'comedy', 'family', 'fantasy']",['US'],NaN,tt0032910,7.5,141937.0,71.160,7.1
tm79357,Bambi,MOVIE,Bambi's tale unfolds from season to season as ...,1942,G,70,"['animation', 'drama', 'family']",['US'],NaN,tt0034492,7.3,140406.0,68.136,7.0
tm62671,Treasure Island,MOVIE,Enchanted by the idea of locating treasure bur...,1950,PG,96,"['family', 'action']","['GB', 'US']",NaN,tt0043067,6.9,8229.0,10.698,6.5

In [25]:
title_basics.drop(title_basics[
    (title_basics.titleType == 'short') |
    (title_basics.titleType == 'tvEpisode') |
    (title_basics.titleType == 'tvSpecial') |
    (title_basics.titleType == 'tvShort') |
    (title_basics.titleType == 'videoGame')
].index, inplace=True)

In [26]:
title_basics.head(10)

,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
tconst,,,,,,,,
tt0000009,movie,Miss Jerry,Miss Jerry,0,1894,\N,45,\N
tt0000502,movie,Bohemios,Bohemios,0,1905,\N,100,\N
tt0000574,movie,The Story of the Kelly Gang,The Story of the Kelly Gang,0,1906,\N,70,\N
tt0000591,movie,The Prodigal Son,L'enfant prodigue,0,1907,\N,90,\N
tt0000615,movie,Robbery Under Arms,Robbery Under Arms,0,1907,\N,\N,\N
tt0000630,movie,Hamlet,Amleto,0,1908,\N,\N,\N
tt0000675,movie,Don Quijote,Don Quijote,0,1908,\N,\N,\N
tt0000679,movie,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays,0,1908,\N,120,\N
tt0000793,movie,Andreas Hofer,Andreas Hofer,0,1909,\N,\N,\N
tt0000814,movie,La bocana de Mar Chica,La bocana de Mar Chica,0,1909,\N,\N,\N

In [ ]:
st.write("Here's our first attempt at using data to create a table:")
st.write(pd.DataFrame({
    'first column': [1, 2, 3, 4],
    'second column': [10, 20, 30, 40]
}))